name: "Bug"
description: "버그가 발생했나요?"
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        [Description] 버그에 대해 설명해주세요.
      placeholder: |
        conflict가 발생했으나 그냥 merge를 해버렸습니다.
  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요
